--ignore RemoteControl/NikRemote_ReaPitch_SetSemitones.lua
--ignore RemoteControl/NikRemote_ReaPitch_ToggleEnable.lua
--ignore RemoteControl/NikRemote_PlayRate_Set.lua
--ignore RemoteControl/NikRemote_PlayRate_TogglePreservePitch.lua
--ignore RemoteControl/Nik_TrackVis_Refresh.lua
--ignore RemoteControl/Nik_Playrate_ReadTempoMap.lua
--ignore RemoteControl/Nik_ProjectTabs_Read.lua
--ignore RemoteControl/Nik_ProjectTabs_Select.lua
--ignore RemoteControl/NikRemote_TabPrev.lua
--ignore RemoteControl/NikRemote_TabNext.lua
--ignore RemoteControl/Nik_Markers_SeekRelative.lua
--ignore RemoteControl/Nik_RemoteControl_GenerateConfig.lua